# Generated by Django 4.2.2 on 2023-06-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard')], max_length=10),
        ),
    ]
